window.rgbToHsv=function(r,g,b){r/=255;g/=255;b/=255;var max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,h=0;if(d!==0){if(max===r)h=((g-b)/d+6)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;}return{h:h,s:max===0?0:d/max,v:max};};

window.rgbToLab=function(r,g,b){r/=255;g/=255;b/=255;r=r>0.04045?Math.pow((r+0.055)/1.055,2.4):r/12.92;g=g>0.04045?Math.pow((g+0.055)/1.055,2.4):g/12.92;b=b>0.04045?Math.pow((b+0.055)/1.055,2.4):b/12.92;var x=r*0.4124+g*0.3576+b*0.1805,y=r*0.2126+g*0.7152+b*0.0722,z=r*0.0193+g*0.1192+b*0.9505;x/=0.95047;z/=1.08883;var f=function(t){return t>0.008856?Math.cbrt(t):7.787*t+16/116;};return{L:116*f(y)-16,a:500*(f(x)-f(y)),b:200*(f(y)-f(z))};};

window.deltaE=function(l1,l2){return Math.sqrt(Math.pow(l1.L-l2.L,2)+Math.pow(l1.a-l2.a,2)+Math.pow(l1.b-l2.b,2));};

window.percentile=function(arr,p){if(!arr.length)return 0;var s=arr.slice().sort(function(a,b){return a-b;});return s[Math.min(Math.floor(s.length*p/100),s.length-1)];};

window.isHeicFile=function(f){var n=(f.name||'').toLowerCase(),m=(f.type||'').toLowerCase();return m==='image/heic'||m==='image/heif'||n.endsWith('.heic')||n.endsWith('.heif');};

window.loadImageFromFile=function(file){return new Promise(function(resolve,reject){var ou=null;try{ou=URL.createObjectURL(file);}catch(e){}if(ou){var i1=new Image(),tm=setTimeout(function(){i1.src='';try{URL.revokeObjectURL(ou);}catch(e){}tryR();},8000);i1.onload=function(){clearTimeout(tm);try{URL.revokeObjectURL(ou);}catch(e){}resolve(i1);};i1.onerror=function(){clearTimeout(tm);try{URL.revokeObjectURL(ou);}catch(e){}tryR();};i1.src=ou;}else{tryR();}function tryR(){var rd=new FileReader();rd.onerror=function(){reject(new Error('reader'));};rd.onload=function(e){var i2=new Image();i2.onerror=function(){reject(new Error('heic_unsupported'));};i2.onload=function(){resolve(i2);};i2.src=e.target.result;};rd.readAsDataURL(file);}});};

window.compressImage=function(file,onStatus){return new Promise(function(resolve,reject){var name=(file.name||'').toLowerCase(),mime=(file.type||'').toLowerCase(),isHeic=window.isHeicFile(file);var allowedMimes=['image/jpeg','image/jpg','image/png','image/gif','image/webp','image/bmp'];var allowedExts=['.jpg','.jpeg','.png','.webp','.gif','.bmp','.heic','.heif'];var ok=allowedMimes.indexOf(mime)!==-1||isHeic||allowedExts.some(function(e){return name.endsWith(e);})||!file.type;if(!ok){reject(new Error('format'));return;}if(file.size>50*1024*1024){reject(new Error('size'));return;}if(isHeic&&onStatus)onStatus('converting');window.loadImageFromFile(file).then(function(img){if(onStatus)onStatus('processing');try{var MAX=800,scale=Math.min(1,MAX/Math.max(img.width,img.height));var w=Math.round(img.width*scale),h=Math.round(img.height*scale);if(!w||!h){reject(new Error('image'));return;}var canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;var ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);try{ctx.getImageData(0,0,1,1);}catch(se){reject(new Error('canvas_security'));return;}resolve({canvas:canvas,w:w,h:h,preview:canvas.toDataURL('image/jpeg',0.82)});}catch(e){reject(new Error('canvas'));}}).catch(function(err){reject(err.message==='heic_unsupported'?new Error('heic_unsupported'):err);});});};

window.getImageData=function(o){return o.canvas.getContext('2d').getImageData(0,0,o.w,o.h);};

window.getErrMsg=function(code,lang){var map={format:'errFormat',size:'errSize',canvas_security:'errSecurity',reader:'errReader',image:'errImage',canvas:'errReader',heic_unsupported:'errHeic'};var key=map[code]||'errReader';return(window.T[lang]||window.T['ru'])[key]||window.T['ru'][key];};

window.isSkinPixel=function(r,g,b){var rgb=(r>95&&g>40&&b>20&&r>g&&r>b&&Math.abs(r-g)>10&&r-b>15);var hsv=window.rgbToHsv(r,g,b);return rgb||(hsv.h>=0&&hsv.h<=55&&hsv.s>=0.08&&hsv.s<=0.80&&hsv.v>=0.25);};

window.getSkinPixels=function(id,cf){cf=cf||0.6;var W=id.width,H=id.height,x0=Math.floor(W*(1-cf)/2),x1=Math.floor(W*(1+cf)/2),y0=Math.floor(H*(1-cf)/2),y1=Math.floor(H*(1+cf)/2),skin=[],d=id.data;for(var y=y0;y<y1;y++)for(var x=x0;x<x1;x++){var i=(y*W+x)*4;if(window.isSkinPixel(d[i],d[i+1],d[i+2]))skin.push({r:d[i],g:d[i+1],b:d[i+2]});}return skin;};

window.COLOR_NAMES={white:{ru:'белый',en:'white'},black:{ru:'чёрный',en:'black'},gray:{ru:'серый',en:'gray'},'dark gray':{ru:'тёмно-серый',en:'dark gray'},'light gray':{ru:'светло-серый',en:'light gray'},red:{ru:'красный',en:'red'},brown:{ru:'коричневый',en:'brown'},'orange-red':{ru:'оранжево-красный',en:'orange-red'},orange:{ru:'оранжевый',en:'orange'},camel:{ru:'верблюжий',en:'camel'},yellow:{ru:'жёлтый',en:'yellow'},beige:{ru:'бежевый',en:'beige'},'yellow-green':{ru:'жёлто-зелёный',en:'yellow-green'},green:{ru:'зелёный',en:'green'},'dark green':{ru:'тёмно-зелёный',en:'dark green'},teal:{ru:'бирюзовый',en:'teal'},blue:{ru:'синий',en:'blue'},'dark blue':{ru:'тёмно-синий',en:'dark blue'},'blue-purple':{ru:'сине-фиолетовый',en:'blue-purple'},purple:{ru:'фиолетовый',en:'purple'},'pink-purple':{ru:'розово-фиолетовый',en:'pink-purple'},pink:{ru:'розовый',en:'pink'}};

window.getColorKey=function(h,s,v){if(s<0.10){if(v>0.85)return'white';if(v<0.18)return'black';return'gray';}if(s<0.20){if(v<0.40)return'dark gray';return'light gray';}if(h<12)return'red';if(h<22)return v<0.5?'brown':'orange-red';if(h<38)return s>0.6?'orange':'camel';if(h<58)return s>0.5?'yellow':'beige';if(h<80)return'yellow-green';if(h<150)return v<0.45?'dark green':'green';if(h<185)return'teal';if(h<220)return v<0.45?'dark blue':'blue';if(h<260)return'blue-purple';if(h<290)return'purple';if(h<320)return'pink-purple';if(h<345)return'pink';return'red';};
